config/routes.rb
Pinpong::Application.routes.draw do
  devise_for :users, skip: :registrations
  root to: "teams#index"

  get '/scores'                     => 'scores#index'
  get 'api/templates/:template'     => 'api/templates#get'
  post 'api/scores/update'           => 'api/score#set_score'

  namespace :api do
    resources :round,       only: [ :show ]
    resources :match,       only: [ :show ] do
      member do
        post :clear_space
      end
    end
    resources :match_set,   only: [ :show ]
    resources :teams,       defaults: {format: :json}
  end

  resources :teams, only: [:index, :new ]
end

app/models/match.rb
class Match < ActiveRecord::Base
  validates_presence_of :match_number

  belongs_to :round,  foreign_key: 'match_round_id',  class_name: 'MatchRound'
  has_many    :sets,  class_name: 'MatchSet', dependent: :delete_all

  has_and_belongs_to_many :teams

  def next_match
    new_match_position = (match_number/2 + match_number%2 )
    round.next_round.matches.find_by(match_number: new_match_position)
  end

  def start
    if teams.count == 2
      3.times { |n| sets.create( set_number: n + 1, position: n + 1 ) }
      sets.each do |set|
        set.scores.create(team: teams.first, position: 1)
        set.scores.create(team: teams.last, position: 2)
      end
    end
  end

  def cancel_match
    sets.delete_all
  end

  def match_winner
    winner = have_winner

    round.advance_from_round winner, next_match
    return winner
  end

  def have_winner
    team_1 = { team: teams.first, wins: 0 }
    team_2 = { team: teams.last,  wins: 0 }

    sets.each do | set |
      if team_1[:team] == set.winner
        team_1[:wins] += 1
      elsif team_2[:team] == set.winner
        team_2[:wins] += 1
      end
    end

    winner = nil 
    winner = team_1[:team] if team_1[:wins] >= 2
    winner = team_2[:team] if team_2[:wins] >= 2

    return winner
  end
end

app/models/match_round.rb
class MatchRound < ActiveRecord::Base
  validates_presence_of :name, :number

  validates :name, inclusion: %w(round\ of\ 16 quarters semifinal final)

  has_many :matches

  scope :round_of_16, -> { find_by(name: 'round of 16') }
  scope :semifinal,   -> { find_by(name: 'semifinal') }
  scope :quarters,    -> { find_by(name: 'quarters') }
  scope :final,       -> { find_by(name: 'final') }

  def next_round
    return MatchRound.find_by(number: number + 1)
  end

  def advance_from_round team, next_match
    unless next_match.teams.count < 2 and next_match.teams.include?(team) or team.nil?
      next_match.teams << team if next_match.teams.count < 2
    end

    if next_match.teams.count == 2 and next_match.sets.empty?
      next_match.start
    end
  end

  def available_matches
    matches.reject{ |m| m.teams.size >= 2 }
  end

end

app/models/match_set.rb
class MatchSet < ActiveRecord::Base
  validates_presence_of :match, :set_number, :position

  has_many :scores, dependent: :delete_all

  belongs_to :match
  belongs_to :winner, foreign_key: 'team_id', class_name: 'Team'

  default_scope order('position ASC')

  def set_winner
    self.winner = scores.order('total DESC').first.team
    save
  end
end

app/models/player.rb
class Player < ActiveRecord::Base

  validates_presence_of :type_account, :user_account, :email

  serialize   :picture_url
  belongs_to  :team
  before_save :set_profile_image

  def is_valid?
    account = type_account == 'twitter' ? (Twitter.users(self.user_account) rescue nil) : (Octokit.user user_account rescue nil)
    account = nil if self.email == ""
    return account.nil? ? false : true
  end

  def set_profile_image
    self.picture_url = type_account == 'twitter' ? (Twitter.users(user_account).first.profile_image_url) : (Octokit.user user_account).avatar_url
  end

end

app/models/score.rb
class Score < ActiveRecord::Base
  validates_presence_of :match_set, :position
  #validates_presence_of :team

  belongs_to :match_set
  belongs_to :team

  default_scope order('position ASC')
end

app/models/team.rb
class Team < ActiveRecord::Base

  validates_presence_of         :name

  has_and_belongs_to_many       :matches

  has_many                      :players

  accepts_nested_attributes_for :players

  has_many                      :scores
  has_many                      :sets, class_name: 'MatchSet'

  mount_uploader :picture, PictureUploader

  def valid_team?
    valid = []
    valid << false if self.name == ""
    players.each do |player|
      valid << player.is_valid?
    end
    (valid.include? false) ? false : true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/match_controller.rb
class Api::MatchController < ApiController
  expose(:match)

  def show
  end

  def clear_space
    Match.find(params[:id]).cancel_match
    respond_to do | format |
      format.json { render json: { status: 202 } }
    end
  end
end

app/controllers/api/match_set_controller.rb
class Api::MatchSetController < ApiController
  expose(:match_set)
end

app/controllers/api/round_controller.rb
class Api::RoundController < ApiController
  include ActionView::Helpers::AssetTagHelper
  expose(:matches) { MatchRound.find_by(number: params[:id]).matches }

  def show
    @champion = MatchRound.final.matches.first.have_winner
  end
end

app/controllers/api/score_controller.rb
class Api::ScoreController < ApiController
  expose(:score)

  def set_score 
    scores = params["set"]["scores"]
    scores.each do | param |
      score = Score.find(param["id"])
      total = param["total"]
      total = 0 if total == nil
      score.update_attributes(total: total)
    end

    set = MatchSet.find(params["set"]["id"])
    match = set.match

    set.set_winner

    match.match_winner if match.have_winner

    respond_to do | format |
      format.json { render json: { status: 202 } }
    end
  end
end

app/controllers/api/teams_controller.rb
class Api::TeamsController < ApiController
  skip_before_filter :verify_authenticity_token
  skip_before_filter :authenticate_user!
  before_filter :fix_params_from_for, only: :create

  expose(:teams)
  expose(:team)

  def index
    render json: teams
  end

  def show
  end

  def create
    match = MatchRound.round_of_16.available_matches.sample
    team = Team.new(team_params)
    if (team.valid_team? && Team.count < 16)
      team.save
      match.teams << team
      match.start if match.teams.count == 2
      redirect_to root_path
    else
      if Team.count == 16
        flash[:top_teams] = "There are 16 teams already, you cannot create another one"
      elsif team.name == ""
        flash[:team] = "You didn't specify a name for your Team" 
      else
        flash[:player1_errors] = "Player 1 was has not a valid account or email" if team.players[0].is_valid? == false || team.players[0].name.nil?
        flash[:player2_errors] = "Player 2 was has not a valid account or email" if team.players[1].is_valid? == false || team.players[1].name.nil?
      end
      redirect_to :back
    end
  end

  def destroy
    if team.delete
      render json: { message: "The Team was successfully deleted"}
    end
  end

  private
  def team_params
    params.require(:team).permit(
      :name, 
      :picture, 
      players_attributes: [
        :type_account, 
        :user_account, 
        :email, 
        :picture_url
      ]
    )
  end

  def fix_params_from_for
    if params[:team][:players_attributes].first.class == Array
      players_attributes = params["team"]["players_attributes"].to_a
      p1_attributes      = players_attributes.first.last
      p2_attributes      = players_attributes.last.last
      params["team"][:players_attributes] = [p1_attributes, p2_attributes]
    end
  end

end

app/controllers/api/templates_controller.rb
class Api::TemplatesController < ApiController
  def get 
    render template: 'api/templates/'+params[:template]+'_template'
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_filter :authenticate_user!
  layout false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def index
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:index, :show]

  expose(:teams)

  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.haml
%div(ng-controller="TemplatesController")
  %div(ng-view)
    %div(ng-include="textTemplate")

app/views/layouts/application.haml
!!!
%html(ng-app="PingPong")
  %head
    %title TangoPong 
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "application/index"
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0' }
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      - if user_signed_in?
        Signed in as #{current_user.email}. Not you?
        \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
    
      .header-titles-container
        =image_tag 'tango-pong-logo.png', class: 'logo'
        %div.hash-tag #someHashTag
    
      %nav
        %ul
          %li
            =link_to 'Teams', teams_path
          %li
            =link_to 'Scores', scores_path
          %li
            =link_to 'Rules', 'application#rules'
    
    #content
      = yield

    %footer
      %p < Playing ping pong at #someHashTag tournament #{link_to 'http://bit.ly/as893fs3', 'http://bit.ly/as893fs3'} >
      #jTweetsAnywhereEndlessScrollingSample      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0' }
    %title MagmaPong 
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      .auth
        - if user_signed_in?
          Signed in as #{current_user.email}. Not you?
          \#{link_to "Sign out", destroy_user_session_path, :method => :delete}
    
      .header-titles-container
        =image_tag 'tango-pong-logo.png', class: 'logo'
        %div.hash-tag #magmaPong    

      %nav
        %ul
          %li
            =link_to 'Teams', teams_path
          %li
            =link_to 'Scores', scores_path if user_signed_in?
          %li
            =link_to 'Rules', 'Rules.pdf'
        - unless flash[:top_teams].nil?
          = content_tag :div, flash[:top_teams], :id => "flash_notice"

    #content
      = yield

    %footer
      #jTweetsAnywhereEndlessScrollingSample      
      %p
        Powered by
        %a{href: "http://www.tangosource.com/", target: "blank"} TangoSource

app/views/scores/index.haml
%div(ng-view)

%script
  if(location.hash === ""){
  location = '#/round/1';
  location.reload();
  }